### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by jhermsmeier**
- reduced overall size (about 0.7 kb less)
- added body base fontsize em calulation
- improved update performance
- only a single id is used now (on the containing div)

### CODE REVIEW

**Comment by VinSpee** [comment]
Woah, fancy guy here :-)

**Comment by davatron5000** [comment]
Wow great.  Really impressive. 2 things I guess
- I'm not really worried about optimizing for filesize. I'd rather optimize for readability. I can work that going forward.
- Should we try to set some standard like passing JSHint?  For that you'd probably need some semicolons.  `with()` also throws an error, but it's probably fine in this circumstance.

Thoughts?

**Comment by jhermsmeier** [comment]
Thanks :)

> I'm not really worried about optimizing for filesize. I'd rather optimize for readability. I can work that going forward.

Alright. I was just thinking about the size, because bookmarklets are subject to URL length restrictions and there's still some logic to be added in regard to issue #3, I guess.
Readability is important too, of course (I thought I maintained readability (did I?); also, I should've kept the comments)

> Should we try to set some standard like passing JSHint? For that you'd probably need some semicolons. `with()` also throws an error, but it's probably fine in this circumstance.

Good idea! Will make the neccessary changes.
We can also get rid of the `with()`, if size isn't important.

**Comment by davatron5000** [comment]
Looks like browsers still do a "divide-by-16" em and not a "body-font-size em": http://codepen.io/davatron5000/pen/xaKoD

**Comment by jhermsmeier** [comment]
Oh, that came as a surprise - it's been over a year...
I deleted the source repository already, so I don't really have an option to commit anymore to this pull request.
That adjustment would have to be taken care of after merging (or, of course, you could throw it in).

**Comment by davatron5000** [comment]
No worries. I'm just cleaning house today. I'll close this. Thanks, tho.

**Pull request closed without merging**
